import { getGeminiClient } from '../../config/gemini.js';
import ChatbotRepository from './chatbot.repository.js';
import ChatbotMapper from './chatbot.mapper.js';
import { SYSTEM_INSTRUCTIONS } from './chatbot.constants.js';
import ApiError from '../../shared/apiError.js';
import { logger } from '../../shared/logger.js';

/**
 * Service Layer for the Chatbot Module.
 */
class ChatbotService {
  /**
   * Retrieve response from Google Gemini API, taking history context into account.
   * @param {ChatMessageInputDTO} inputDto
   * @param {string} userId
   * @returns {Promise<ChatMessageResponseDTO>}
   */
  async processUserMessage(inputDto, userId) {
    logger.info('Processing chatbot message request...', { userId, sessionId: inputDto.sessionId });

    // 1. Fetch recent conversation history tail to provide context (last 15 turns)
    const recentLogs = await ChatbotRepository.fetchHistory(userId, inputDto.sessionId, 15);

    // 2. Format history turns for Google Gemini multi-turn chat SDK
    const historyContext = [];
    for (const turn of recentLogs) {
      historyContext.push({ role: 'user',  parts: [{ text: turn.message }] });
      historyContext.push({ role: 'model', parts: [{ text: turn.reply   }] });
    }

    try {
      // 3. Get lazily-initialised Gemini client (reads key from process.env NOW)
      const genAI = getGeminiClient();

      const modelName = process.env.GEMINI_MODEL || 'gemini-2.0-flash';
      const model = genAI.getGenerativeModel({
        model: modelName,
        systemInstruction: SYSTEM_INSTRUCTIONS
      });

      // 4. Start a multi-turn chat session with injected context
      const chatSession = model.startChat({
        history: historyContext,
        generationConfig: {
          maxOutputTokens: 1500,
          temperature: 0.7
        }
      });

      // 5. Call Gemini with automatic retry on 429 rate-limit (up to 3 attempts)
      let result;
      const maxRetries = 3;
      for (let attempt = 1; attempt <= maxRetries; attempt++) {
        try {
          const aiPromise      = chatSession.sendMessage(inputDto.message);
          const timeoutPromise = new Promise((_, reject) =>
            setTimeout(() => reject(new Error('Gemini API request timed out after 25 s')), 25000)
          );
          result = await Promise.race([aiPromise, timeoutPromise]);
          break; // success — exit retry loop
        } catch (retryErr) {
          const isRateLimit = retryErr.message?.includes('429') || retryErr.message?.includes('quota') || retryErr.message?.includes('Resource');
          if (isRateLimit && attempt < maxRetries) {
            const waitMs = attempt * 3000; // 3s, 6s back-off
            logger.warn(`Gemini 429 rate-limit hit. Retrying in ${waitMs}ms (attempt ${attempt}/${maxRetries})...`);
            await new Promise(resolve => setTimeout(resolve, waitMs));
          } else {
            throw retryErr;
          }
        }
      }

      const botReply = result.response.text();

      if (!botReply || botReply.trim() === '') {
        throw ApiError.internal('Gemini returned an empty reply.');
      }

      logger.info('AI reply generated by Gemini successfully.');

      // 6. Persist this interaction in MongoDB
      const entity = ChatbotMapper.toEntity(inputDto, userId, botReply);
      await ChatbotRepository.saveMessage(entity);

      return ChatbotMapper.toResponseDTO(botReply);

    } catch (error) {
      logger.error('Error during chatbot AI generation', error);

      // Parse Gemini's suggested retry delay if present (e.g. "Please retry in 28.5s")
      const retryMatch = error.message?.match(/Please retry in ([\d.]+)s/);
      const retrySec   = retryMatch ? Math.ceil(parseFloat(retryMatch[1])) : null;

      // Daily quota exhausted (limit: 0)
      if (error.message?.includes('limit: 0') || error.message?.includes('PerDay')) {
        const msg = retrySec
          ? `Daily AI quota exhausted. Gemini suggests retrying in ${retrySec} seconds. Please try again shortly or generate a new API key at https://aistudio.google.com/apikey`
          : 'Daily AI quota exhausted. Please try again tomorrow or generate a new API key at https://aistudio.google.com/apikey';
        throw new ApiError(429, msg);
      }

      // Per-minute rate limit
      if (error.message?.includes('429') || error.message?.includes('quota') || error.message?.includes('Resource')) {
        const msg = retrySec
          ? `AI rate limit hit. Please wait ${retrySec} seconds and try again.`
          : 'Too many requests. Please wait a moment and try again.';
        throw new ApiError(429, msg);
      }

      // Timeout
      if (error.message?.includes('timed out')) {
        throw new ApiError(504, 'AI engine timed out. Please resend your message.');
      }

      // API key or config error bubbled up from getGeminiClient()
      if (error.message?.includes('GEMINI_API_KEY') || error.message?.includes('not configured')) {
        throw ApiError.internal('Gemini API key is not configured. Set GEMINI_API_KEY in the .env file.');
      }

      throw ApiError.internal('Failed to generate assistant reply.', { detail: error.message });
    }
  }

  /**
   * Fetch conversation history for the authenticated user.
   */
  async getUserChatHistory(userId, sessionId = 'default', limit = 50) {
    logger.info('Retrieving chat history logs...', { userId, sessionId, limit });
    const records = await ChatbotRepository.fetchHistory(userId, sessionId, limit);
    return ChatbotMapper.toHistoryDTOList(records);
  }

  /**
   * Delete conversation history for the authenticated user.
   */
  async clearUserChatHistory(userId, sessionId = 'default') {
    logger.info('Clearing chat history logs...', { userId, sessionId });
    await ChatbotRepository.clearHistory(userId, sessionId);
    return true;
  }
}

export default new ChatbotService();
